# Generated by Django 6.0.3 on 2026-03-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF с подробным описанием проекта', null=True, upload_to='projects/pdfs/', verbose_name='PDF-файл с проектом'),
        ),
    ]
