# Generated by Django 6.0.3 on 2026-03-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/pdfs/', verbose_name='PDF-файл с проектом'),
        ),
    ]
