# Generated by Django 6.0.3 on 2026-03-03 14:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за м²')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('includes_measure', models.BooleanField(default=False, verbose_name='Обмерный план')),
                ('includes_layout', models.BooleanField(default=False, verbose_name='Разработка планировки')),
                ('includes_installation', models.BooleanField(default=False, verbose_name='Монтаж')),
                ('includes_plumbing', models.BooleanField(default=False, verbose_name='Сантехника')),
                ('includes_3d_layout', models.BooleanField(default=False, verbose_name='Объемная планировка')),
                ('includes_collage', models.BooleanField(default=False, verbose_name='Коллаж')),
                ('includes_electric', models.BooleanField(default=False, verbose_name='Электрика')),
                ('includes_floors', models.BooleanField(default=False, verbose_name='План полов')),
                ('includes_ceilings', models.BooleanField(default=False, verbose_name='План потолков')),
                ('includes_materials', models.BooleanField(default=False, verbose_name='Отделочные материалы')),
                ('includes_walls', models.BooleanField(default=False, verbose_name='Развертки стен')),
                ('includes_3d', models.BooleanField(default=False, verbose_name='3D визуализация')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
    ]
