# Generated by Django 6.0.3 on 2026-03-03 14:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер этапа')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('icon', models.CharField(default='fa-solid fa-pen-ruler', max_length=50, verbose_name='Иконка (FontAwesome)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
                'ordering': ['order'],
            },
        ),
    ]
